language: python
sudo: required

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  - export LUA_PATH="$LUA_PATH;./?.lua;./?/init.lua"

install:
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - lua ./lib/lunar/lunarc/init.lua
  - chmod +x ./install.sh
  - sudo ./install.sh

script:
  - lunarc
  - busted --verbose --coverage

after_success:
  - luacov-coveralls -r ./lunar -e $TRAVIS_BUILD_DIR/lua_install -e "_spec"
